export const en = {
  'properties-must-object': 'The input parameter must be an object.',
  'invalid-rules': 'Rules :name: is not valid.',

  'required': ':attribute: must not be empty.',
  'email': 'The format of :attribute: is not valid.',
  'url': 'The entered :attribute: is not valid.',
  'phone': ':attribute: must be a valid mobile number.',
  'min': ':attribute: must be at least :min: characters long.',
  'max': ':attribute: must be at most :max: characters long.',
  'length': ':attribute: must be :len: characters long.',
  'regex': ':attribute: is not valid.',
  'same': ':attribute: must be equal to :same:.',
  'starts': ':attribute: must start with the letter :starts:.',
  'ends': ':attribute: must end with the letter :ends:.',
  'integer': ':attribute: must be an integer.',
  'exists': ':attribute: must exist in the list: :exists:.',
  'not_exists': ':attribute: must not exist in the list: :exists:.',
  'extensions': ':attribute: must have one of the following extensions: :extensions:.',
  'mimes': ':attribute: must be of one of the following types: :mimes:.',
  'image': ':attribute: must be a valid image file.',
  'file': ':attribute: must be a file.',
  'size': ':attribute: must have a size that meets the specified criteria. (:operator:, :args:)',
  'type': ':attribute: must be of type :type:.',
  'is_true': ':attribute: must be true.',
  'is_false': ':attribute: must be false.',
}

export const fa = {
  'properties-must-object': 'پارامتر ورودی باید یک شیء باشد.',
  'invalid-rules': 'قوانین :name: معتبر نیستند.',

  'required': ':attribute: نباید خالی باشد.',
  'email': 'فرمت :attribute: معتبر نیست.',
  'url': ':attribute: وارد شده معتبر نیست.',
  'phone': ':attribute: باید یک شماره موبایل معتبر باشد.',
  'min': ':attribute: باید حداقل :min: کاراکتر طول داشته باشد.',
  'max': ':attribute: باید حداکثر :max: کاراکتر طول داشته باشد.',
  'length': ':attribute: باید :len: کاراکتر طول داشته باشد.',
  'regex': ':attribute: معتبر نیست.',
  'same': ':attribute: باید برابر با :same: باشد.',
  'starts': ':attribute: باید با حرف :starts: شروع شود.',
  'ends': ':attribute: باید با حرف :ends: پایان یابد.',
  'integer': ':attribute: باید یک عدد صحیح باشد.',
  'exists': ':attribute: باید در لیست وجود داشته باشد: :exists:.',
  'not_exists': ':attribute: نباید در لیست وجود داشته باشد: :exists:.',
  'extensions': ':attribute: باید یکی از پسوندهای زیر را داشته باشد: :extensions:.',
  'mimes': ':attribute: باید از یکی از انواع زیر باشد: :mimes:.',
  'image': ':attribute: باید یک فایل تصویر معتبر باشد.',
  'file': ':attribute: باید یک فایل باشد.',
  'size': ':attribute: باید اندازه‌ای داشته باشد که با معیارهای مشخص شده مطابقت داشته باشد. (:operator:, :args:)',
  'type': ':attribute: باید از نوع :type: باشد.',
  'is_true': ':attribute: باید درست باشد.',
  'is_false': ':attribute: باید نادرست باشد.',
}

export const ar = {
  'properties-must-object': 'يجب أن يكون معلمة الإدخال كائنًا.',
  'invalid-rules': 'القواعد :name: غير صالحة.',

  'required': ':attribute: يجب ألا تكون فارغة.',
  'email': 'تنسيق :attribute: غير صالح.',
  'url': ':attribute: المدخل غير صالح.',
  'phone': ':attribute: يجب أن يكون رقم هاتف محمول صالح.',
  'min': ':attribute: يجب أن يكون طوله على الأقل :min: حرفًا.',
  'max': ':attribute: يجب أن يكون طوله بحد أقصى :max: حرفًا.',
  'length': ':attribute: يجب أن يكون طوله :len: حرفًا.',
  'regex': ':attribute: غير صالح.',
  'same': ':attribute: يجب أن يكون مساويًا لـ :same:.',
  'starts': ':attribute: يجب أن يبدأ بالحرف :starts:.',
  'ends': ':attribute: يجب أن ينتهي بالحرف :ends:.',
  'integer': ':attribute: يجب أن يكون عددًا صحيحًا.',
  'exists': ':attribute: يجب أن يوجد في القائمة: :exists:.',
  'not_exists': ':attribute: يجب ألا يوجد في القائمة: :exists:.',
  'extensions': ':attribute: يجب أن يحتوي على أحد الامتدادات التالية: :extensions:.',
  'mimes': ':attribute: يجب أن يكون من أحد الأنواع التالية: :mimes:.',
  'image': ':attribute: يجب أن يكون ملف صورة صالح.',
  'file': ':attribute: يجب أن يكون ملفًا.',
  'size': ':attribute: يجب أن يكون له حجم يتوافق مع المعايير المحددة. (:operator:, :args:)',
  'type': ':attribute: يجب أن يكون من النوع :type:.',
  'is_true': ':attribute: يجب أن يكون صحيحًا.',
  'is_false': ':attribute: يجب أن يكون خاطئًا.',
}

export const tr = {
  'properties-must-object': 'Girdi parametresi bir nesne olmalıdır.',
  'invalid-rules': 'Kurallar :name: geçerli değil.',

  'required': ':attribute: boş olmamalıdır.',
  'email': ':attribute: formatı geçerli değil.',
  'url': 'Girilen :attribute: geçerli değil.',
  'phone': ':attribute: geçerli bir cep telefonu numarası olmalıdır.',
  'min': ':attribute: en az :min: karakter uzunluğunda olmalıdır.',
  'max': ':attribute: en fazla :max: karakter uzunluğunda olmalıdır.',
  'length': ':attribute: :len: karakter uzunluğunda olmalıdır.',
  'regex': ':attribute: geçerli değil.',
  'same': ':attribute: :same: ile eşit olmalıdır.',
  'starts': ':attribute: :starts: harfi ile başlamalıdır.',
  'ends': ':attribute: :ends: harfi ile bitmelidir.',
  'integer': ':attribute: bir tam sayı olmalıdır.',
  'exists': ':attribute: listede bulunmalıdır: :exists:.',
  'not_exists': ':attribute: listede bulunmamalıdır: :exists:.',
  'extensions': ':attribute: aşağıdaki uzantılardan birine sahip olmalıdır: :extensions:.',
  'mimes': ':attribute: aşağıdaki türlerden birine ait olmalıdır: :mimes:.',
  'image': ':attribute: geçerli bir resim dosyası olmalıdır.',
  'file': ':attribute: bir dosya olmalıdır.',
  'size': ':attribute: belirtilen kriterlere uygun bir boyuta sahip olmalıdır. (:operator:, :args:)',
  'type': ':attribute: :type: türünde olmalıdır.',
  'is_true': ':attribute: doğru olmalıdır.',
  'is_false': ':attribute: yanlış olmalıdır.',
}
